<a href="https://colab.research.google.com/github/nexageapps/AI/blob/main/Basic%20%7C%20L1%20-%20Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
a = tf.constant([[1,2,3],[4,5,9]])
b = tf.constant([[4,5,1],[10,20,0]])

print("a+b is ", tf.add(a,b))
print("a*b is ", tf.multiply(a,b))

a+b is  tf.Tensor(
[[ 5  7  4]
 [14 25  9]], shape=(2, 3), dtype=int32)
a*b is  tf.Tensor(
[[  4  10   3]
 [ 40 100   0]], shape=(2, 3), dtype=int32)
