<a href="https://colab.research.google.com/github/nexageapps/AI/blob/main/Basic/B01%20-%20Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 1: Arithmetic Operations for AI

**Author:** Karthik Arjun  
**LinkedIn:** [karthik-arjun-a5b4a258](https://www.linkedin.com/in/karthik-arjun-a5b4a258/)  
**Created:** 2026  
**Updated:** 2026

## What are Tensors?

In AI and machine learning, **tensors** are the fundamental data structure. Think of them as bucket for numbers:

- **Scalar** (0D tensor): A single number → `5`
- **Vector** (1D tensor): A list of numbers → `[1, 2, 3]`
- **Matrix** (2D tensor): A table of numbers → `[[1, 2], [3, 4]]`
- **Higher dimensions**: 3D, 4D, etc. (used for images, videos)

Neural networks process data using tensors and perform mathematical operations on them.

In [ ]:
import sys
print("Python:", sys.executable)

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

## 1. Understanding Tensor Shapes

Let's start by creating different types of tensors and understanding their shapes.

In [ ]:
# Scalar (0D tensor)
scalar = tf.constant(5)
print("Scalar:", scalar)
print("Shape:", scalar.shape)
print()

# Vector (1D tensor)
vector = tf.constant([1, 2, 3, 4])
print("Vector:", vector)
print("Shape:", vector.shape, "(4 elements)")
print()

# Matrix (2D tensor)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape, "(2 rows, 3 columns)")

## 2. Element-wise Operations

These operations work on corresponding elements (same position) in tensors.

### Addition
```
[1, 2] + [4, 5] = [1+4, 2+5] = [5, 7]
```

In [ ]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 9]])
b = tf.constant([[4, 5, 1],
                 [10, 20, 0]])

print("Matrix a:")
print(a)
print("\nMatrix b:")
print(b)
print("\nElement-wise Addition (a + b):")
print(tf.add(a, b))
# Can also use: a + b

### Element-wise Multiplication
```
[1, 2] * [4, 5] = [1×4, 2×5] = [4, 10]
```
**Note:** This is NOT matrix multiplication!

In [1]:
# Cell 1: Import TensorFlow
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

a = tf.constant([1, 2])
b = tf.constant([4, 5])

# Element-wise multiplication
print("Element-wise multiplication:")
print(tf.multiply(a, b))  # or a * b
# Result: [4, 10]

# Matrix multiplication - COMMENTED OUT because it would error
# tf.matmul(a, b)  # This would error - incompatible shapes




2026-03-01 16:26:17.698620: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.16.1
Element-wise multiplication:
tf.Tensor([ 4 10], shape=(2,), dtype=int32)


## 3. Matrix Multiplication (The AI Essential!)

Matrix multiplication is the **core operation** in neural networks. It's how we compute:
- **Inputs × Weights = Outputs**

### Rules:
- For matrices A (m×n) and B (p×q) to multiply:
  - **n must equal p** (inner dimensions must match)
  - Result will be (m×q)

### Example:
```
A (2×3) @ B (3×2) = C (2×2) ✓
A (2×3) @ B (2×3) = Error ✗ (3 ≠ 2)
```

### How it works:
```
[1, 2]   [5]     [1×5 + 2×6]   [17]
       @ [6]  =               = 
```

In [10]:
# Matrix multiplication example
# a is (2×3), we need to multiply by (3×2) to get (2×2)
# We'll transpose b to make it (3×2)
# Cell 1: Import TensorFlow
import tensorflow as tf
from tabulate import tabulate

a = tf.constant([[1, 2, 3],
                 [4, 5, 9]]) 
b = tf.constant([[4, 5, 1], 
                 [10, 20, 0]])

print("Matrix a shape:", a.shape, "(2 rows, 3 columns)")
print("Matrix b transposed shape:", tf.transpose(b).shape, "(3 rows, 2 columns)")
print()


print("Matrix a:")
print(tabulate(a.numpy(), tablefmt='grid'))
print(f"\n Matrix b:")
print(tabulate(tf.transpose(b).numpy(), tablefmt='grid'))


# Matrix multiplication 
result = tf.matmul(a, tf.transpose(b))
# Can also use: a @ tf.transpose(b)

print("\n Matrix Multiplication (a @ b.T):")
print(tabulate(result.numpy(), tablefmt='fancy_grid'))
print("Result shape:", result.shape, "(2×2)")

Matrix a shape: (2, 3) (2 rows, 3 columns)
Matrix b transposed shape: (3, 2) (3 rows, 2 columns)

Matrix a:
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 4 | 5 | 9 |
+---+---+---+

 Matrix b:
+---+----+
| 4 | 10 |
+---+----+
| 5 | 20 |
+---+----+
| 1 |  0 |
+---+----+

 Matrix Multiplication (a @ b.T):
╒════╤═════╕
│ 17 │  50 │
├────┼─────┤
│ 50 │ 140 │
╘════╧═════╛
Result shape: (2, 2) (2×2)


### Let's verify one calculation manually:
```
First element of result:
[1, 2, 3] @ [4, 10] = 1×4 + 2×5 + 3×1 = 4 + 10 + 3 = 17 ✓
              [5, 20]
              [1, 0]
```

In [13]:
# Manual verification
manual_calc = 1*4 + 2*5 + 3*1
print(f"Manual calculation: {manual_calc}")
print(f"Matrix multiplication result [0,0]: {result[0,0].numpy()}")
print(f"Match: {manual_calc == result[0,0].numpy()}")

Manual calculation: 17
Matrix multiplication result [0,0]: 17
Match: True


## 4. Why Matrix Multiplication Matters in AI

In a neural network:
```
Input features × Weights = Output
```

Example: Predicting house price from 3 features

In [20]:
# Input: [square_feet, bedrooms, age]
house_features = tf.constant([[2000.0, 3.0, 10.0]])  # 1 house, 3 features

# Weights learned by the model
weights = tf.constant([[150.0],    # price per sq ft
                       [20000.0],  # price per bedroom
                       [-5000.0]]) # price reduction per year

# Prediction = features @ weights
predicted_price = tf.matmul(house_features, weights)

print("House features:", house_features.numpy())
print("Weights:", weights.numpy().flatten())
print(f"\nPredicted price: ${predicted_price[0,0].numpy():,.2f}")
print(f"\nCalculation: 2000×150 + 3×20000 + 10×(-5000) = ${predicted_price.numpy()[0,0]:,.2f}")

House features: [[2000.    3.   10.]]
Weights: [  150. 20000. -5000.]

Predicted price: $310,000.00

Calculation: 2000×150 + 3×20000 + 10×(-5000) = $310,000.00


## 5. Practice Exercises

Try these on your own:

1. Create two matrices of shape (3×2) and add them
2. Create a matrix (2×4) and multiply it with a matrix (4×3) - what's the result shape?
3. What happens if you try to multiply (2×3) with (2×3)? Try it!
4. Create a simple neural network calculation with 4 input features and 2 outputs

In [ ]:
# Practice code here
------------------------------------------------------------------------------------

#1. Create two matrices of shape (3×2) and add them
import tensorflow as tf;
input1 = tf.constant([    [1,2,3] , 
                          [4,5,6] ])
input2 = tf.constant([    [7,8,9] , 
                          [10,11,12] ])
result = tf.add(input1, input2)
print(f"Addition Result: ${result.numpy()}")

------------------------------------------------------------------------------------
#2. Create a matrix (2×4) and multiply it with a matrix (4×3) - what's the result shape?
#import tensorflow as tf;
input3 = tf.constant([   [1,2,3,4] , 
                         [5,6,7,8],
                         ])
input4 = tf.constant([   [9, 10, 11] , 
                         [12, 13, 14,] , 
                         [15, 16, 17],
                         [18,19,20] ])

result2 = tf.matmul(input3, input4)
print(f"\n Multiplication Shape is: ${result2.shape}")
print(f" Multiplication Result is: ${result2}")

------------------------------------------------------------------------------------
#3. What happens if you try to multiply (2×3) with (2×3)? Try it!
#Error - Matrix dimensions are not match 

------------------------------------------------------------------------------------
# 4. Create a simple neural network calculation with 4 input features and 2 outputs
# Example: Student result prediction for Math and English

# Input: [hours_studied, hours_slept, attendance_rate, previous_score]
# Each row = one input feature
student_features = tf.constant([[20.0, 8.0, 0.95, 75.0]])  # 1 student, 4 features

# Weights learned by the model (4 features → 2 outputs)
# Column 0 = Math weights, Column 1 = English weights
weights = tf.constant([[1.0, 0.8],      # hours_studied weight (max input: 40)
                       [2.0, 1.5],      # hours_slept weight (max input: 12)
                       [20.0, 25.0],    # attendance_rate weight (max input: 1.0)
                       [0.2, 0.3]])     # previous_score weight (max input: 100)

# Step 1: Matrix multiplication (features @ weights)
predicted_scores = tf.matmul(student_features, weights)  # Shape: (1, 2)

print("Raw predicted scores:", predicted_scores.numpy())

# Step 2: Apply constraints to keep scores in 0-100 range
# Clip scores: minimum 0, maximum 100
final_scores = tf.clip_by_value(predicted_scores, 0.0, 100.0)

# Extract individual scores
math_score = final_scores.numpy()[0, 0]
english_score = final_scores.numpy()[0, 1]

# Determine pass/fail (passing score = 60)
math_result = "Pass" if math_score >= 60 else "Fail"
english_result = "Pass" if english_score >= 60 else "Fail"

# Display results
print("\n" + "="*60)
print("STUDENT SCORE PREDICTION")
print("="*60)
print("\nInput Features:")
print(f"  Hours Studied: {student_features.numpy()[0, 0]}")
print(f"  Hours Slept: {student_features.numpy()[0, 1]}")
print(f"  Attendance Rate: {student_features.numpy()[0, 2]*100:.0f}%")
print(f"  Previous Score: {student_features.numpy()[0, 3]}")

print("\nWeights Matrix Shape:", weights.shape, "(4 inputs → 2 outputs)")

print("\nPredicted Scores:")
print(f"  Math: {math_score:.2f} - {math_result}")
print(f"  English: {english_score:.2f} - {english_result}")

print("\nCalculation Breakdown:")
print(f"  Math Score = 20×1.0 + 8×2.0 + 0.95×20.0 + 75×0.2")
print(f"             = 20 + 16 + 19 + 15")
print(f"             = {math_score:.2f}")
print(f"\n  English Score = 20×0.8 + 8×1.5 + 0.95×25.0 + 75×0.3")
print(f"                = 16 + 12 + 23.75 + 22.5")
print(f"                = {english_score:.2f}")




Addition Result: $[[ 8 10 12]
 [14 16 18]]

 Multiplication Shape is: $(2, 3)
 Multiplication Result is: $[[150 160 170]
 [366 392 418]]
Raw predicted scores: [[70.   74.25]]

STUDENT SCORE PREDICTION

Input Features:
  Hours Studied: 20.0
  Hours Slept: 8.0
  Attendance Rate: 95%
  Previous Score: 75.0

Weights Matrix Shape: (4, 2) (4 inputs → 2 outputs)

Predicted Scores:
  Math: 70.00 - Pass
  English: 74.25 - Pass

Calculation Breakdown:
  Math Score = 20×1.0 + 8×2.0 + 0.95×20.0 + 75×0.2
             = 20 + 16 + 19 + 15
             = 70.00

  English Score = 20×0.8 + 8×1.5 + 0.95×25.0 + 75×0.3
                = 16 + 12 + 23.75 + 22.5
                = 74.25


## Key Takeaways

1. **Tensors** are the fundamental data structure in AI
2. **Element-wise operations** (`+`, `*`) work on corresponding elements
3. **Matrix multiplication** (`@` or `tf.matmul`) is different and requires matching dimensions
4. **Matrix multiplication is how neural networks compute outputs from inputs**
5. Always check tensor shapes - most errors come from dimension mismatches!

## Next Steps

In the next lesson, we'll explore how these operations are used in building actual neural network layers!